### ISSUE TITLE
泥猴哇

### ISSUE THREAD

**Issue by JamCh01** [littlemo/littlemo.github.io#1]
# 听说Markdown很难用诶
##### 以及是gogs咩～

**Comment by littlemo** [comment]
之前开发一个封装库用Sphinx写的文档，然后我就发现。。。
Markdown就是个战五渣。。。。

准备过年期间把以前用Markdown写的blog都重写一遍= =

**Comment by JamCh01** [comment]
不应该是写一个markdown2reStructuredText（好吧这么名字先忽略掉）工具么= =

**Comment by littlemo** [comment]
你用一个功能少的标记语言转到一个功能多的标记语言，显示效果一样，转换的意义在哪里？
装个Markdown解析工具不转直接生成Html用不就好了= =

重写可以给现有的blog文章应用更丰富的语言表述，以及结构索引

**Comment by JamCh01** [comment]
我去看看reStructuredText（逃
